### ISSUE TITLE
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

### ISSUE THREAD

**Issue by TalBarami** [open-mmlab/mmaction2#1351]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

The following error appears upon finishing epoch 240 (last one):
`Default process group has not been initialized, please make sure to call init_process_group.`

Additionally, it seems as if the classifier does not learn at all - accuracy remains the same as it was in the first steps even after 240 epochs.
**Reproduction**

1. What command or script did you run?

```
python train.py
configs/skeleton/posec3d/my_config.py
--work-dir
work_dirs/my_workdir
--validate
--test-best
--gpus
1
--seed
0
--deterministic
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

Only the configuration changes mentioned in:
https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/custom_dataset_training.md

3. What dataset did you use?

A private dataset of real people performing several pre-defined types of repetitive actions. This dataset contains approximately 5000 samples with 13 different classes.

**Environment**

```
'tail' is not recognized as an internal or external command,
operable program or batch file.
'gcc' is not recognized as an internal or external command,
operable program or batch file.
sys.platform: win32
Python: 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 3080
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
NVCC: Not Available
GCC: n/a
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.11.1
OpenCV: 4.5.4
MMCV: 1.3.8
MMCV Compiler: MSVC 192829912
MMCV CUDA Compiler: 11.3
MMAction2: 0.20.0+61d7eb8
```
**Error traceback**

If applicable, paste the error traceback here.

```
021-12-23 22:57:06,396 - mmaction - INFO - 
top1_acc	0.2789
top5_acc	0.7224
2021-12-23 22:57:06,396 - mmaction - INFO - Evaluating mean_class_accuracy ...
2021-12-23 22:57:06,398 - mmaction - INFO - 
mean_acc	0.0769
2021-12-23 22:57:06,398 - mmaction - INFO - Epoch(val) [240][98]	top1_acc: 0.2789, top5_acc: 0.7224, mean_class_accuracy: 0.0769
2021-12-23 22:57:08,563 - mmaction - INFO - 972 videos remain after valid thresholding
2021-12-23 22:57:08,564 - mmaction - INFO - load checkpoint from E:\mmaction2\work_dirs\autism_center\best_top1_acc_epoch_20.pth
2021-12-23 22:57:08,564 - mmaction - INFO - Use load_from_local loader
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 972/972, 1.1 task/s, elapsed: 907s, ETA:     0sTraceback (most recent call last):
  File "E:/mmaction2/tools/train.py", line 201, in <module>
    main()
  File "E:/mmaction2/tools/train.py", line 197, in main
    meta=meta)
  File "E:\mmaction2\mmaction\apis\train.py", line 254, in train_model
    gpu_collect)
  File "C:\Users\owner\anaconda3\envs\mmlab\lib\site-packages\mmcv\engine\test.py", line 86, in multi_gpu_test
    results = collect_results_cpu(results, len(dataset), tmpdir)
  File "C:\Users\owner\anaconda3\envs\mmlab\lib\site-packages\mmcv\engine\test.py", line 129, in collect_results_cpu
    dist.barrier()
  File "C:\Users\owner\anaconda3\envs\mmlab\lib\site-packages\torch\distributed\distributed_c10d.py", line 2708, in barrier
    default_pg = _get_default_group()
  File "C:\Users\owner\anaconda3\envs\mmlab\lib\site-packages\torch\distributed\distributed_c10d.py", line 411, in _get_default_group
    "Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

Process finished with exit code 1

```
I couldn't identify the cause for this error, nor the reason for the low accuracy. Other skeleton-based algorithms managed to learn on this dataset.

Thanks in advance!

**Comment by kennymckormick** [comment]
For the first error, there seems to be something wrong with the --test-best flag, you can test manually for now and I will try to find the problem. 
For the second problem (model not learning anything), you can paste your config file and one data sample here. I will try to figure out the reason.

**Comment by TalBarami** [comment]
Hey @kennymckormick , thanks a lot for assisting me.
I'll try to remove the --test-best flag and handle it manually and update you as soon as I finish training.

In the meantime, here you may find the configuration file:
```
model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ResNet3dSlowOnly',
        depth=50,
        pretrained=None,
        in_channels=17,
        base_channels=32,
        num_stages=3,
        out_indices=(2, ),
        stage_blocks=(4, 6, 3),
        conv1_stride_s=1,
        pool1_stride_s=1,
        inflate=(0, 1, 1),
        spatial_strides=(2, 2, 2),
        temporal_strides=(1, 1, 2),
        dilations=(1, 1, 1)),
    cls_head=dict(
        type='I3DHead',
        in_channels=512,
        num_classes=13,
        spatial_type='avg',
        dropout_ratio=0.5),
    train_cfg=dict(),
    test_cfg=dict(average_clips='prob'))

dataset_type = 'PoseDataset'
ann_file_train = 'data/my_dataset/train.pkl'
ann_file_val = 'data/my_dataset/val.pkl'
ann_file_test = 'data/my_dataset/test.pkl'
left_kp = [1, 3, 5, 7, 9, 11, 13, 15]
right_kp = [2, 4, 6, 8, 10, 12, 14, 16]
train_pipeline = [
    dict(type='UniformSampleFrames', clip_len=48),
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1., allow_imgpad=True),
    dict(type='Resize', scale=(-1, 64)),
    dict(type='RandomResizedCrop', area_range=(0.56, 1.0)),
    dict(type='Resize', scale=(56, 56), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5, left_kp=left_kp, right_kp=right_kp),
    dict(
        type='GeneratePoseTarget',
        sigma=0.6,
        use_score=True,
        with_kp=True,
        with_limb=False),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
val_pipeline = [
    dict(type='UniformSampleFrames', clip_len=48, num_clips=1, test_mode=True),
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1., allow_imgpad=True),
    dict(type='Resize', scale=(-1, 64)),
    dict(type='CenterCrop', crop_size=64),
    dict(
        type='GeneratePoseTarget',
        sigma=0.6,
        use_score=True,
        with_kp=True,
        with_limb=False),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
test_pipeline = [
    dict(
        type='UniformSampleFrames', clip_len=48, num_clips=10, test_mode=True),
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1., allow_imgpad=True),
    dict(type='Resize', scale=(-1, 64)),
    dict(type='CenterCrop', crop_size=64),
    dict(
        type='GeneratePoseTarget',
        sigma=0.6,
        use_score=True,
        with_kp=True,
        with_limb=False,
        double=True,
        left_kp=left_kp,
        right_kp=right_kp),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
data = dict(
    videos_per_gpu=8,
    workers_per_gpu=2,
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix='',
        class_prob={i: 1 + int(i >= 60)
                    for i in range(120)},
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix='',
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix='',
        pipeline=test_pipeline))
# optimizer

optimizer = dict(
    type='SGD', lr=0.2, momentum=0.9,
    weight_decay=0.0003)  # this lr is used for 8 gpus
optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))
# learning policy
lr_config = dict(policy='CosineAnnealing', by_epoch=False, min_lr=0)
total_epochs = 240
checkpoint_config = dict(interval=10)
workflow = [('train', 10)]
evaluation = dict(
    interval=10,
    metrics=['top_k_accuracy', 'mean_class_accuracy'],
    topk=(1, 5))
log_config = dict(
    interval=20, hooks=[
        dict(type='TextLoggerHook'),
    ])
dist_params = dict(backend='nccl')
log_level = 'INFO'
workdir = './work_dirs/my_dataset'
# work_dir = './work_dirs/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint'
load_from = None
resume_from = None
find_unused_parameters = False
```

I'm unable to share the original video sample, but I can share the output of `ntu_pose_extraction.py`  - you may find two samples [here](https://drive.google.com/drive/folders/1JERaFGkCbvaif0BZbd0eEBaz13YCaflx?usp=sharing). One where a figure in the scene is clapping and in the other a figure jumps.

**Comment by kennymckormick** [comment]
Not sure, seems everything OK. BTW, have you set `img_shape` and `original_shape` as the real video shape (height, width) for each video?

**Comment by TalBarami** [comment]
Yeah both shapes are similar as the real video shape.

**Comment by kennymckormick** [comment]
Hello, the test-best flag is fixed in our latest PR #1362

**Comment by JXIONG008** [comment]
> Hello, the test-best flag is fixed in our latest PR #1362

Hi, I still encounter the same error msg after updating with a similar situation: error appears upon finishing the last epoch, but the accuarcy is updating normally.

**Comment by kennymckormick** [comment]
P

> > Hello, the test-best flag is fixed in our latest PR #1362
> 
> Hi, I still encounter the same error msg after updating with a similar situation: error appears upon finishing the last epoch, but the accuarcy is updating normally.

One possible reason is that multiple processes are out of sync here:

https://github.com/open-mmlab/mmaction2/blob/6ec1af71562c1e4f145cc74b36ee815ae85ae216/mmaction/apis/train.py#L205

Some processes try to find the best checkpoint in the work_dir. However, the checkpoint has not been written to ur filesystem yet by process 0. I have added a barrier after `runner.run`, maybe you can have another try.

**Comment by liu-bill666** [comment]
@JXIONG008  

I have the same problem as you. Have you solved it？

**Comment by Stella-Hxy** [comment]
> Not sure, seems everything OK. BTW, have you set `img_shape` and `original_shape` as the real video shape (height, width) for each video?
Thank you very much for your work and answers. Where should I set the `img_shape` and `original_shape` in code？

**Comment by kennymckormick** [comment]
> > Not sure, seems everything OK. BTW, have you set `img_shape` and `original_shape` as the real video shape (height, width) for each video?
> 
> Thank you very much for your work and answers. Where should I set the `img_shape` and `original_shape` in code？Cause I met the same error running slowfast model in my own dataset.

Sorry, the answer seems to be not related to your problem: setting video shape is just required for PoseC3D models.

**Comment by FarzanehAskari** [comment]
I have the same error for PoseC3D. The model is saved correctly and you can run inference on it. However, the training doesn't log (log files are corrupted and no training accuracy is saved) and doesn't show the process on the terminal.

**Comment by michael-camilleri** [comment]
I have the same runtime error:

```RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.```

I am running trainign with 1 GPU on 1 Machine (just to try things out). Any idea what could be causing this?

**Comment by kennymckormick** [comment]
The problems have been fixed now. BTW, we highly recommend users to use distributed training and testing (you can use it even if you have only 1 GPU). The command for distributed training is just like:

bash tools/dist_train.sh {config} {num_gpus} {other_args ...}

**Comment by poem2018** [comment]
> The problems have been fixed now. BTW, we highly recommend users to use distributed training and testing (you can use it even if you have only 1 GPU). The command for distributed training is just like:
> 
> bash tools/dist_train.sh {config} {num_gpus} {other_args ...}

Hi, I still met the "Default process group has not been initialized, " error when I run the mmaction2_tutorial.ipynb file with the latest version's code. The accuracy is normal, but training shows the error in the 10th epoch.

**Comment by kennymckormick** [comment]
> > The problems have been fixed now. BTW, we highly recommend users to use distributed training and testing (you can use it even if you have only 1 GPU). The command for distributed training is just like:
> > bash tools/dist_train.sh {config} {num_gpus} {other_args ...}
> 
> Hi, I still met the "Default process group has not been initialized, " error when I run the mmaction2_tutorial.ipynb file with the latest version's code. The accuracy is normal, but training shows the error in the 10th epoch.

Has this problem fixed by PR #1459?

**Comment by vasanth4224** [comment]
(open-mmlab) a@r4611:/media/a/2TB/Skeleton_Action_Recognition/mmaction2-master$ bash tools/dist_train.sh configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoints.py --work-dir work_dirs1/slowonly_r50_u48_240e_ntu120_xsub_keypoints --validate --test-best --gpus 1 --seed 0 --deterministic
/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
Traceback (most recent call last):
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 564, in determine_local_world_size
    return int(nproc_per_node)
ValueError: invalid literal for int() with base 10: '--work-dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 709, in run
    config, cmd, cmd_args = config_from_args(args)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 617, in config_from_args
    nproc_per_node = determine_local_world_size(args.nproc_per_node)
  File "/home/a/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 582, in determine_local_world_size
    raise ValueError(f"Unsupported nproc_per_node value: {nproc_per_node}")
ValueError: Unsupported nproc_per_node value: --work-dir

Hi @kennymckormick, when I executed dist_train, I got this error. Can you please help me to fix this error?

**Comment by kennymckormick** [comment]
It should be:

`bash tools/dist_train.sh configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoints.py **{number_of_gpus}** --work-dir work_dirs1/slowonly_r50_u48_240e_ntu120_xsub_keypoints --validate --test-best --gpus 1 --seed 0 --deterministic`

You miss the number of gpus in your command.
